FROM python:3.10
# Set working directory to /home/cskim/docker-project/fastapi
WORKDIR /home/cskim/docker-project/fastapi

# Copy the contents of the current local directory into the container’s working directory
ADD . /home/cskim/docker-project/fastapi

# Run a command
CMD ["python", "hello.py"]
